name: ci.yml
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  java-test:
    uses: ./.github/workflows/java-test-reusable.yml

  docker-ci:
    needs: java-test
    uses: ./.github/workflows/docker-ci-reusable.yml
    permissions:
      contents: read
      actions: write